# Aula 10/11 - *Machine Learning*

**Objetivo**: Aprender o que é *Machine Learning* e quais são os componentes de um algoritmo de ML.

## Defininição - *Machine Learning*

*Machine Learning* é uma área de estudo que fornece aos computadores a habilidade de aprender sem serem explicitamente programados.

> Um programa de computador que aprende a partir da experiência E em relação a algum tipo de tarefa T e alguma medida de desempenho P, se o seu desempenho em T, conforme medido por P, melhora com a experiência E.

Mitchell, T. M. (1997). Machine Learning. McGraw-Hill, New York.

### Experiência (E)

Em *Machine Learning* um programa de computador aprende sem ser explicitamente programado. Ele aprende a partir de um conjunto de dados que expressa toda *experiência* (E) que desejamos ensina-lo. Esse conjunto de dados é chamado de **conjunto de treinamento**. 

* **Aprendizagem Supervisionada**: o conjunto de treinamento é composto por amostras de entradas/saídas.
* **Aprendizagem Não-Supervisionada**:  conjunto de treinamento é composto por amostras de entradas apenas.

### Tarefas (T)

* Classificação - Supervisionada qualitativa
* Regressão - Supervisionada quantitativa
* Agrupamento - Não-supervisionada

### Desempenho (P)

Para medir o desempenho de um algoritmo de Machine Learning é preciso de uma medida de desempenho para mensurar a qualidade do processo de aprendizagem. Essa medida é conhecida como **função de custo** ou **função de erro**. Essa função é definida de acordo com o tipo de problema (aprendizagem supervisionada ou não-supervisionada). Essa função contém um **conjunto de parâmetros** a serem otimizada pelo um algoritmo de *Machine Learning*.

De maneira geral, pode-se dizer que o objetivo do algoritmo de *Machine Learning* é otimizar (aprender) o **conjunto de parâmetros** de tal forma que resultado da função seja o mínimo possível. Isso significa que algoritmo tem uma alta taxa de aprendizagem e uma baixa taxa de erro.

* Dividir os dados em
* Treino
* Teste
    * Aqui eu mensuro desempenho (P)

<img src="https://www.edsonmelo.com.br/dados_csv/images/train-test.png" alt="train-test" style="width: 400px;"/>

### Exemplo: jogo de computador
- Tarefa $T$ é jogar xadrez. 
- Medida de desempenho $P$ é uma relação entre partidas ganhas contra oponentes versus perdidas. 
- Experiência $E$ é prática de partidas concluídas. Note que, estas esperiências são descritas em um conjunto de dados chamado de **conjunto de treinamento**.

#### Tente responder: Classifique as sentenças a baixo como: Tarefa $T$, Experiências $E$ e Medida de desempenho $P$

- Classificar emails como spam ou não spam ?
- Verificar quais emails o usuário classifica como spam ?
- O número (ou fração) de emails corretamente classificados como spam ou não spam ?

## Generalização

A habilidade de desempenhar bem em dados não observados anteriormente.

Mensurada por erro:
* Dados de Treino: Erro de Treino
* Dados de Teste: Erro de Teste

### Erro do Algoritmo

2 Fatores:

1. Habilidade de Reduzir o Erro de Treino
2. Habilidade de Reduzir a Lacuna entre o Erro de Treino e o Erro de Teste

<img src="https://www.edsonmelo.com.br/dados_csv/images/train-vs-test-error.png" alt="train-vs-test-error" style="width: 400px;"/>

<img src="https://www.edsonmelo.com.br/dados_csv/images/trainin4.gif" alt="training" style="width: 500px;"/>

### *Overfitting* e *Underfitting*

* Centrais em *Machine Learning*
* Underfitting
    - Modelos **menos** flexíveis que o ideal
* Overfitting
    - Modelos **mais** flexíveis que o ideal   

<img src="https://www.edsonmelo.com.br/dados_csv/images/underfitting-overfitting-capacity.png" alt="underfitting-overfitting-capacity" style="width: 500px;"/>

#### No Free Lunch Theorem (NFL)

> “Se você faz nenhum pressuposto dos dados, não há razão para preferir um modelo por outro”

> Wolpert, D. H. (1996). The Lack of a Priori Distinctions between Learning Algorithms. Neural Computation, 8(7), 1341–1390. https://doi.org/10.1162/neco.1996.8.7.1341
	
* Nenhum modelo é garantido que funcionará melhor
    * Ex: para alguns dados, regressão linear é melhor; para outros, redes neurais.
* A única maneira de saber é avaliar todos os modelos
* Por isso que não há *almoço grátis*

## Otimização

Método mais utilizado é o **Método do Gradiente** (*Gradient Descent*)

Inventado em 1847 por Augustin-Louis Cauchy. Usa a derivativa para minimizar uma função-alvo.

**Método iterativo**: a cada iteração, tenta ir para o local/global minima

<img src="https://www.edsonmelo.com.br/dados_csv/images/gradient-descent.png" alt="gradient-descent" style="width: 400px;"/>

<img src="https://www.edsonmelo.com.br/dados_csv/images/gradient-descent.gif" alt="gradient-descent-animation" style="width: 500px;"/>

<img src="https://www.edsonmelo.com.br/dados_csv/images/gradient-descent-2.gif" alt="gradient-descent-animation" style="width: 500px;"/>

### Local/Global Minima/Maxima

<img src="https://www.edsonmelo.com.br/dados_csv/images/local-minima.png" alt="local-minima" style="width: 400px;"/>

<img src="https://www.edsonmelo.com.br/dados_csv/images/gradient-descent-1.gif" alt="gradient-descent-animation-2" style="width: 500px;"/>

<img src="https://www.edsonmelo.com.br/dados_csv/images/gradient-descent-3.gif" alt="gradient-descent-animation-3" style="width: 500px;"/>

### Tipos de Método do Gradiente (*Gradient Descent*)

* *Batch Gradient Descent*: Dataset todo
* *Stochastic Gradient Descent*: Um exemplo aleatório do Dataset
* *Mini-batch Gradient Descent*: Amostras aleatórias do Dataset


<img src="https://www.edsonmelo.com.br/dados_csv/images/grad-descent-methods.png" alt="grad-descent-methods" style="width: 500px;"/>

# Mãos a Obra
## Definindo, Classificando, Aprendendo, Predizendo e Analisando Resultados

<p>Machine Learning é uma técnica de Inteligência Artificial que permite que a máquina aprenda através de exemplos, exatamente como os seres humanos.</p>

* Os emails do Gmail já são classificados automaticamente como <strong>Spam</strong> ou <strong>Não Spam</strong>.<br>
* O Facebook já é capaz de identificar o rosto de cada um dos seus amigos e marcá-los automaticamente nas fotos do rolê do final de semana.<br>
* Quando você faz uma compra online e recebe sugestões de produtos que foram selecionados por uma máquina que se baseia nas suas escolhas anteriores.

# Definição do problema

* o que queremos classificar?
* quais características diferenciam o conjunto?
* falsos positivos e falsos negativos
* eliminação de objetos (se não é um gato, então é um cachorro)

### Pergunta: você sabe identificar o que é um gato ou um cachorro?

<p>Vamos tomar o <strong>gato</strong> como referência!!!</p>
<p> A <strong><em>Priori</strong></em> vamos selecionar três gatos para descrever nosso conjunto e tabular três características:</p>

<table>
    <tr>
        <td colspan="4"  align="center">GATOS</td>
    </tr>
    <tr>
        <td>Animal</td>
        <td>É fofinho?</td>
        <td>Tem orelha pequena?</td>
        <td>Faz miau?</td>
    </tr>
    <tr>
        <td>Gato 1</td>
        <td align="center">1</td>
        <td align="center">1</td>
        <td align="center">1</td>
    </tr>
    <tr>
        <td>Gato 2</td>
        <td align="center">1</td>
        <td align="center">0</td>
        <td align="center">1</td>
    </tr>
    <tr>
        <td>Gato 3</td>
        <td align="center">0</td>
        <td align="center">1</td>
        <td align="center">1</td>
    </tr>
</table>

<p>Vamos definir agora nosso cachorros.</p>
<table>
    <tr>
        <td colspan="4"  align="center">CACHORROS</td>
    </tr>
    <tr>
        <td>Animal</td>
        <td>É fofinho?</td>
        <td>Tem orelha pequena?</td>
        <td>Faz miau?</td>
    </tr>
    <tr>
        <td>Cachorro 1</td>
        <td align="center">1</td>
        <td align="center">1</td>
        <td align="center">0</td>
    </tr>
    <tr>
        <td>Cachorro 2</td>
        <td align="center">0</td>
        <td align="center">1</td>
        <td align="center">0</td>
    </tr>
    <tr>
        <td>Cachorro 3</td>
        <td align="center">0</td>
        <td align="center">1</td>
        <td align="center">0</td>
    </tr>
</table>

In [ ]:
# Função para mostrar os resultados "humanos" (-1 e 1)
def legenda(lista):
  retorno = []
  lista_animais = [ [1, 'Gato'], [-1, 'Cachorro'] ]
  for l in lista:
    if l == 1:
      retorno.append(lista_animais[0][1]) # Gato
    else:
      retorno.append(lista_animais[1][1]) # Cachorro
  return retorno

#Montando o Problema

In [ ]:
# Transformar a informação em uma estrutura processável
# gatos
animal1	= [1,	1, 1]
animal2	= [1, 0, 1]
animal3	= [0, 1, 1]

#cachorros
animal4 =	[1, 1, 0]
animal5 = [0, 1, 0]
animal6 = [0, 1, 0]

# Definição do Conjunto de Dados





In [ ]:
animais = [animal1, animal2, animal3, animal4, animal5,animal6]

#Informando para o Algoritmo quem é gato e quem é cachorro

In [ ]:
# 1 é gato
# -1 é cachorro
convencao_animais = [1, 1, 1, -1, -1, -1]

# Aplicando os Modelos Machine Learning
Diferentes abordagens: SVM, Árvores de decisão, K-Nearest Neighbors, Naive Bayes, entre outros.

In [ ]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [ ]:
# treinamento para aprendizagem
modelo_mnb = MultinomialNB() # definição do modelo de aprendizagem

# realizando a aprendizagem (.fit(value_1, value_2))
modelo_mnb.fit(animais, convencao_animais)

MultinomialNB()

In [ ]:
# verificando os coeficientes de aprendizagem
modelo_mnb.coef_

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:103: FutureWarning: Attribute `coef_` was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


array([[-1.2039728 , -1.2039728 , -0.91629073]])

# Realizando Predições

Agora que o algoritmo já __aprendeu__ o que é um gato e o que é um cachorro, vamos predizer três animais que __não__ pertencem ao conjunto de dados original.

<table>
    <tr>
        <td colspan="4"  align="center">ANIMAIS</td>
    </tr>
    <tr>
        <td>Animal</td>
        <td>É fofinho?</td>
        <td>Tem orelha pequena?</td>
        <td>Faz miau?</td>
    </tr>
    <tr>
        <td>teste_1</td>
        <td align="center">1</td>
        <td align="center">1</td>
        <td align="center">1</td>
    </tr>
    <tr>
        <td>teste_2</td>
        <td align="center">1</td>
        <td align="center">0</td>
        <td align="center">0</td>
    </tr>
    <tr>
        <td>teste_3</td>
        <td align="center">0</td>
        <td align="center">0</td>
        <td align="center">1</td>
    </tr>
</table>

In [ ]:
# criando o conjunto de dados para realizar a predição
teste_1 = [1, 1, 1]
teste_2 = [1, 0, 0]
teste_3 = [0, 0, 1]
dados_teste = [teste_1, teste_2, teste_3]

In [ ]:
# realizando a predição (.predict(value))
modelo_mnb.predict(dados_teste)

array([1, 1, 1])

In [ ]:
# Nesta prtedição, o algoritmo NB tem um sucesso de 66% de acerto.
legenda(modelo_mnb.predict(dados_teste))

['Gato', 'Gato', 'Gato']

# Análise dos resultados

* De antemão já sabíamos que deveria ser _Gato_, _Cachorro_ e _Gato_, mas a resposta foi: _Gato_, _Gato_ e _Gato_.
Portanto, a acurácia do algoritmo é de 66%, ou seja, acertou dois em três, o que é considerado bom.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

# Definindo os novos modelos

In [ ]:
tree = DecisionTreeClassifier(max_depth=10) # árvore de decisão
knn = KNeighborsClassifier(n_neighbors=5) # vizinho mais próximo
logreg = LogisticRegression() # regressão logística
gnb = GaussianNB() # gaussiana

teste_1 = [1, 1, 1]
teste_2 = [1, 0, 0]
teste_3 = [0, 0, 1]
dados_teste = [teste_1, teste_2, teste_3]

In [ ]:
# Atividade
# Treinar os modelos acima e fazer a predição para cada um deles
# Qual modelo de ML (Machine Learning) teve melhor desempenho?

GaussianNB()

In [ ]:
# Regressão Logística
logreg.fit(animais, convencao_animais)
legenda(logreg.predict(dados_teste))
logreg.coef_

array([[ 0.25209419, -0.28956175,  1.05431824]])

In [ ]:
# Árvore de Decisão
tree.fit(animais, convencao_animais)
legenda(tree.predict(dados_teste))
tree.score

<bound method ClassifierMixin.score of DecisionTreeClassifier(max_depth=10)>

In [ ]:
# Vizinho Próximo
knn.fit(animais, convencao_animais)
legenda(knn.predict(dados_teste))

['Gato', 'Cachorro', 'Gato']

In [ ]:
# Gaussian
gnb.fit(animais, convencao_animais)
legenda(gnb.predict(dados_teste))

['Gato', 'Cachorro', 'Gato']